# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'OauthClientCredentials',
]

@pulumi.output_type
class OauthClientCredentials(dict):
    def __init__(__self__, *,
                 oauth_client_id: builtins.str,
                 oauth_client_secret: builtins.str,
                 oauth_token_endpoint: builtins.str,
                 endpoint_params: Optional[Mapping[str, builtins.str]] = None,
                 oauth_scopes: Optional[Sequence[builtins.str]] = None):
        """
        :param builtins.str oauth_client_id: client id
        :param builtins.str oauth_client_secret: client secret
        :param builtins.str oauth_token_endpoint: oauth token endpoint
        :param Mapping[str, builtins.str] endpoint_params: Additional key/values to pass to the underlying Oauth client library (as EndpointParams)
        :param Sequence[builtins.str] oauth_scopes: scopes
        """
        pulumi.set(__self__, "oauth_client_id", oauth_client_id)
        pulumi.set(__self__, "oauth_client_secret", oauth_client_secret)
        pulumi.set(__self__, "oauth_token_endpoint", oauth_token_endpoint)
        if endpoint_params is not None:
            pulumi.set(__self__, "endpoint_params", endpoint_params)
        if oauth_scopes is not None:
            pulumi.set(__self__, "oauth_scopes", oauth_scopes)

    @property
    @pulumi.getter(name="oauthClientId")
    def oauth_client_id(self) -> builtins.str:
        """
        client id
        """
        return pulumi.get(self, "oauth_client_id")

    @property
    @pulumi.getter(name="oauthClientSecret")
    def oauth_client_secret(self) -> builtins.str:
        """
        client secret
        """
        return pulumi.get(self, "oauth_client_secret")

    @property
    @pulumi.getter(name="oauthTokenEndpoint")
    def oauth_token_endpoint(self) -> builtins.str:
        """
        oauth token endpoint
        """
        return pulumi.get(self, "oauth_token_endpoint")

    @property
    @pulumi.getter(name="endpointParams")
    def endpoint_params(self) -> Optional[Mapping[str, builtins.str]]:
        """
        Additional key/values to pass to the underlying Oauth client library (as EndpointParams)
        """
        return pulumi.get(self, "endpoint_params")

    @property
    @pulumi.getter(name="oauthScopes")
    def oauth_scopes(self) -> Optional[Sequence[builtins.str]]:
        """
        scopes
        """
        return pulumi.get(self, "oauth_scopes")


