# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .get_object import *
from .object import *
from .provider import *
from ._inputs import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_restapi.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_restapi.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "restapi",
  "mod": "index/object",
  "fqn": "pulumi_restapi",
  "classes": {
   "restapi:index/object:Object": "Object"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "restapi",
  "token": "pulumi:providers:restapi",
  "fqn": "pulumi_restapi",
  "class": "Provider"
 }
]
"""
)
